services:
  - type: web
    name: subtitle-extractor
    runtime: python
    region: frankfurt
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y \
        tesseract-ocr \
        tesseract-ocr-ara \
        tesseract-ocr-eng \
        tesseract-ocr-rus \
        tesseract-ocr-tur \
        tesseract-ocr-hin \
        tesseract-ocr-urd \
        libgl1-mesa-glx \
        libglib2.0-0 && \
      pip install -r streamlit-app/requirements.txt
    startCommand: streamlit run streamlit-app/main.py --server.port $PORT --server.address 0.0.0.0 --server.headless true --server.enableCORS false --server.enableXsrfProtection false
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
